---
abstract: 'A glimpse at an Enlightened Perl.'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Kensho
no_index:
  directory:
    - inc
    - t
requires:
  App::Ack: 0
  App::cpanminus: 0
  App::perlbrew: 0
  Bundle::LWP: 0
  CGI::FormBuilder::Source::Perl: 0
  CHI: 0
  CPAN::Uploader: 0
  Carp::Always: 0
  Config::Any: 0
  Config::General: 0
  DBD::SQLite: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  Date::Tiny: 0
  DateTime: 0
  DateTime::Tiny: 0
  Devel::Cover: 0
  Devel::NYTProf: 0
  Devel::REPL: 0
  Dist::Zilla: 0
  Email::Sender: 0
  Email::Valid: 0
  HTTP::Lite: 0
  IO::All: 0
  LWP::Simple: 0
  MIME::Types: 0
  Modern::Perl: 0
  Module::CoreList: 0
  Module::Install: 0
  POE: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Perl::Version: 0
  Pod::Readme: 0
  SQL::Translator: 0
  Smart::Comments: 0
  Software::License: 0
  Spreadsheet::ParseExcel::Simple: 0
  Task::Catalyst: 0
  Task::Moose: 0
  Template: 0
  Term::ProgressBar::Simple: 0
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::Most: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
  Text::CSV_XS: 0
  Time::ParseDate: 0
  Time::Tiny: 0
  Try::Tiny: 0
  TryCatch: 0
  WWW::Mechanize: 0
  WWW::Mechanize::TreeBuilder: 0
  XML::Atom: 0
  XML::Generator::PerlData: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  XML::RSS: 0
  XML::SAX: 0
  XML::SAX::Writer: 0
  local::lib: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perigrin/task-kensho.git
version: 0.23
